parameters:
  name: ''
  vmImage: ''
  toolchain: 'stable'
  features: 'all'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  variables:
    tc: ${{ parameters.toolchain }}
    features: ${{ parameters.features }}
  steps: # TODO: Add installing of dependencies in the future
  - powershell: |
      Invoke-WebRequest -Uri "https://win.rustup.rs" -OutFile "rustup-init.exe"
      &".\rustup-init.exe" --default-toolchain $(tc) -y
    displayName: 'Install rust'
  - powershell: |
      If ("$(features)" -eq "all") {
        &"$env:USERPROFILE\.cargo\bin\cargo" build --all-features
      }
      Else {
        &"$env:USERPROFILE\.cargo\bin\cargo" build --no-default-features --features "$(features)"
      }
    displayName: 'Build Serenity'
  - powershell: |
      If ("$(features)" -eq "all") {
        &"$env:USERPROFILE\.cargo\bin\cargo" test --all-features
      }
      Else {
        &"$env:USERPROFILE\.cargo\bin\cargo" test --no-default-features --features "$(features)"
      }
    displayName: 'Test Serenity'
